"""
Module: backend/app/schemas/data_contracts
Purpose:
    Defines all shared data contracts (Pydantic models) used as frozen data structures 
    across TERA V2 module boundaries.
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class TokenLogprob(BaseModel):
    """Represents a generated token and its associated natural log probability.

    Attributes:
        token (str): The generated string token representation.
        logprob (float): The natural log probability of the token choice.
    """
    token: str = Field(
        ..., 
        description="The generated string token representation."
    )
    logprob: float = Field(
        ..., 
        description="The natural log probability of the token choice."
    )

class RawModelOutput(BaseModel):
    """Contains raw text completion and token log probability telemetry from inference.

    Attributes:
        text (str): The raw text output generated by the language model completion.
        tokens (List[TokenLogprob]): List of tokens and their associated log probabilities.
        latency_ms (float): Total inference execution time in milliseconds.
        usage_tokens (int): Total number of tokens consumed during completion generation.
    """
    text: str = Field(
        ..., 
        description="The raw text output generated by the language model completion."
    )
    tokens: List[TokenLogprob] = Field(
        default_factory=list, 
        description="List of tokens and their associated log probabilities."
    )
    latency_ms: float = Field(
        ..., 
        gt=0.0, 
        description="Total inference execution time in milliseconds."
    )
    usage_tokens: int = Field(
        ..., 
        ge=0, 
        description="Total number of tokens consumed during completion generation."
    )
    external_api_calls: int = Field(
        default=0,
        description="Number of external API calls made during this inference."
    )

class VerificationConstraints(BaseModel):
    """Defines output constraints and schemas to validate LLM generations.

    Attributes:
        json_schema (Optional[Dict[str, Any]]): OpenAPI or JSON Schema dictionary structure.
        regex_pattern (Optional[str]): Optional regular expression pattern the output must match.
        stop_sequences (List[str]): List of stop sequences that should have terminated the output.
        min_length_chars (Optional[int]): Optional minimum length constraint in characters.
        max_length_chars (Optional[int]): Optional maximum length constraint in characters.
    """
    json_schema: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Pydantic or OpenAPI schema to validate JSON responses against."
    )
    regex_pattern: Optional[str] = Field(
        default=None,
        description="Optional regular expression pattern that the response must match."
    )
    stop_sequences: List[str] = Field(
        default_factory=list,
        description="List of stop sequences that should have terminated the output."
    )
    min_length_chars: Optional[int] = Field(
        default=None,
        ge=0,
        description="Optional minimum length constraint in characters for the response."
    )
    max_length_chars: Optional[int] = Field(
        default=None,
        gt=0,
        description="Optional maximum length constraint in characters for the response."
    )

class VerificationResult(BaseModel):
    """Stores the aggregated results of the ROVL verification pipeline.

    Attributes:
        passed (bool): True if completion passes all syntax, logic, and entropy checks.
        average_surprisal (float): The calculated average token-level surprisal.
        sequence_entropy (float): The sequence-level mean Shannon entropy.
        failed_validators (List[str]): Array of validator labels that rejected the output.
    """
    passed: bool = Field(
        ..., 
        description="True if completion passes all syntax, logic, and entropy checks."
    )
    average_surprisal: float = Field(
        ..., 
        description="The calculated average token-level surprisal."
    )
    sequence_entropy: float = Field(
        ..., 
        description="The sequence-level mean Shannon entropy."
    )
    failed_validators: List[str] = Field(
        default_factory=list, 
        description="Array of validator labels that rejected the output."
    )

class InferenceRequest(BaseModel):
    """Represents a standard inference request payload.

    Attributes:
        prompt (str): The raw prompt text submitted to the orchestrator.
        task_id (str): Structured identifier matching task pattern: task_<index>_<hash>.
        c2 (float): Token cost factor of the local cheap model tier.
        c3 (float): Token cost factor of the remote dense model tier.
        lambda_coeff (float): Tradeoff parameter between cost minimization and accuracy.
        alpha_dense (float): Profiled baseline accuracy of the dense model for this task domain.
        schema_type (str): Target structure schema constraint type (none, json, regex).
        regex_pattern (Optional[str]): Compiled regular expression pattern if schema_type is regex.
    """
    prompt: str = Field(
        ..., 
        min_length=1, 
        description="The raw prompt text submitted to the orchestrator."
    )
    task_id: str = Field(
        ..., 
        pattern=r"^task_\d+_[a-zA-Z0-9]+$", 
        description="Structured identifier matching task pattern: task_<index>_<hash>."
    )
    source_task_id: Optional[str] = Field(
        default=None,
        min_length=1,
        description="Original dataset task ID used for results and telemetry joins."
    )
    c2: float = Field(
        ..., 
        ge=0.0, 
        description="Token cost factor of the local cheap model tier."
    )
    c3: float = Field(
        ..., 
        ge=0.0, 
        description="Token cost factor of the remote dense model tier."
    )
    lambda_coeff: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Tradeoff parameter between cost minimization and accuracy maximization."
    )
    alpha_dense: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Profiled baseline accuracy of the dense model for this task domain."
    )
    schema_type: str = Field(
        default="none", 
        description="Target structure schema constraint type (none, json, regex)."
    )
    regex_pattern: Optional[str] = Field(
        default=None, 
        description="Compiled regular expression pattern required if schema_type is regex."
    )
    category: str = Field(
        default="unknown",
        description="The task category."
    )

class InferenceResponse(BaseModel):
    """Represents the finalized inference response returned by the orchestrator.

    Attributes:
        final_response (str): The final text completion output.
        route_taken (str): The chosen execution route (cache, solver, local_llm, remote_fallback).
        verification (Optional[VerificationResult]): Audit metrics from the ROVL pipeline.
        tokens_consumed (int): Total competition token cost billed.
        latency_ms (float): End-to-end processing time in milliseconds.
    """
    final_response: str = Field(
        ..., 
        description="The final text completion output."
    )
    route_taken: str = Field(
        ..., 
        description="The chosen execution route (cache, solver, local_llm, remote_fallback)."
    )
    verification: Optional[VerificationResult] = Field(
        default=None, 
        description="Audit metrics from the ROVL pipeline."
    )
    tokens_consumed: int = Field(
        ..., 
        ge=0, 
        description="Total competition token cost billed."
    )
    latency_ms: float = Field(
        ..., 
        gt=0.0, 
        description="End-to-end processing time in milliseconds."
    )

class TelemetryLog(BaseModel):
    """Represents a flat telemetry record exported to telemetry.json.

    Attributes:
        task_id (str): The unique task identifier.
        route_taken (str): The finalized execution route taken.
        verification_passed (bool): True if output passed verification.
        m2_tokens (int): Tokens consumed locally (cheap tier).
        m3_tokens (int): Tokens consumed remotely (dense tier).
        del_bypass (bool): True if bypassed to programmatic solver.
        cache_hit (bool): True if resolved by Semantic Cache.
        latency_ms (float): Total elapsed time in milliseconds.
    """
    task_id: str = Field(..., description="The unique task identifier.")
    route_taken: str = Field(..., description="The finalized execution route taken.")
    verification_passed: bool = Field(..., description="True if output passed verification.")
    m2_tokens: int = Field(default=0, description="Tokens consumed locally (cheap tier).")
    m3_tokens: int = Field(default=0, description="Tokens consumed remotely (dense tier).")
    del_bypass: bool = Field(default=False, description="True if bypassed to programmatic solver.")
    cache_hit: bool = Field(default=False, description="True if resolved by Semantic Cache.")
    latency_ms: float = Field(..., description="Total elapsed time in milliseconds.")
    
    # Strict TERA V3 Telemetry fields
    fast_local_tokens: int = Field(default=0, description="Tokens generated by fast local vLLM.")
    local_power_tokens: int = Field(default=0, description="Tokens generated by power local vLLM.")
    external_tokens: int = Field(default=0, description="Tokens from non-local APIs only.")
    external_api_calls: int = Field(default=0, description="Count of non-local inference calls only.")
    fireworks_tokens: int = Field(default=0, description="Fireworks-specific external tokens.")

    # Extended metrics for benchmark audits
    category: str = Field(default="unknown", description="The task category.")
    route_selected: str = Field(default="unknown", description="The route selected by the router.")
    cache_hit_or_miss: str = Field(default="miss", description="Whether this request was a cache hit or miss.")
    deterministic_solver_used: Optional[str] = Field(default=None, description="The deterministic solver used, if any.")
    local_model_used: Optional[str] = Field(default=None, description="The local model used, if any.")
    local_latency_ms: float = Field(default=0.0, description="The latency of the local model, if any.")
    local_completion_length: int = Field(default=0, description="The character length of the local completion.")
    rovl_verdict: str = Field(default="skipped", description="The verification verdict of the ROVL validator.")
    exact_rovl_rejection_reason: List[str] = Field(default_factory=list, description="The list of ROVL validator failures.")
    timeout_status: bool = Field(default=False, description="Whether the local request timed out.")
    remote_fallback_triggered: bool = Field(default=False, description="Whether the remote fallback was triggered.")
    final_correctness: Optional[bool] = Field(default=None, description="Whether the final answer was correct.")
    failure_category: str = Field(default="none", description="The failure category, if incorrect.")

    # New optional cascade routing fields
    difficulty_tier: Optional[str] = Field(default=None, description="The difficulty tier.")
    routing_reasons: List[str] = Field(default_factory=list, description="Reasons for routing selection.")
    cisc_enabled: bool = Field(default=False, description="Whether CISC was enabled.")
    sample_count: int = Field(default=0, description="Number of cheap samples generated.")
    agreement_type: Optional[str] = Field(default=None, description="Type of agreement/consensus.")
    agreement_score: float = Field(default=0.0, description="Consensus agreement score.")
    did_refine: bool = Field(default=False, description="Whether refinement was performed.")
    refinement_passed: Optional[bool] = Field(default=None, description="Whether refinement succeeded.")
    enriched_handoff_used: bool = Field(default=False, description="Whether enriched handoff was used.")
    cascade_fallback_used: bool = Field(default=False, description="Whether fallback to legacy path was activated.")

