from pydantic import BaseModel, Field
from typing import Any, Dict

class RouteRequest(BaseModel):
    """
    Schema for a routing and execution request.
    """
    prompt: str = Field(
        ..., 
        description="The user prompt to be routed and processed by TERA."
    )
    context: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Optional metadata or execution context for the router."
    )


class RoutingDecision(BaseModel):
    """
    Schema for routing metadata returned by the router engine.
    """
    selected_model: str = Field(
        ..., 
        description="The model name selected for execution (e.g., M2 or M3)."
    )
    confidence: float = Field(
        ..., 
        description="Calibrated confidence probability of successful completion by the cheap model."
    )
    route: str = Field(
        ..., 
        description="The execution path chosen (e.g., 'cheap', 'dense', 'cascade')."
    )
    rationale: str = Field(
        ..., 
        description="A human-readable explanation of why this route was selected."
    )


class TokenStats(BaseModel):
    """
    Schema for tracking token consumption and savings.
    """
    input_tokens: int = Field(0, description="Number of input/prompt tokens.")
    output_tokens: int = Field(0, description="Number of output/completion tokens.")
    total_tokens: int = Field(0, description="Total tokens consumed.")
    saved_tokens: int = Field(0, description="Number of tokens saved versus running only the dense model.")


class CostStats(BaseModel):
    """
    Schema for tracking cost and savings.
    """
    estimated_cost_usd: float = Field(0.0, description="Estimated execution cost in USD.")
    saved_cost_usd: float = Field(0.0, description="Estimated USD saved compared to the baseline.")


class RouteResponse(BaseModel):
    """
    Schema for the final API response.
    """
    response: str = Field(
        ..., 
        description="The text response generated by the selected model."
    )
    routing_decision: RoutingDecision = Field(
        ..., 
        description="The routing decision details."
    )
    tokens: TokenStats = Field(
        ..., 
        description="Token usage stats for this request."
    )
    cost: CostStats = Field(
        ..., 
        description="Cost stats for this request."
    )
